import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";
import logo from "../images/logo.svg";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "h-screen flex flex-col")}>
        <header className="flex p-6 bg-white">
          <Image src={logo} unoptimized alt="Logo" />
        </header>
        {children}
      </body>
    </html>
  );
}
